namespace Vertical.CommandLine;

internal static class SourceBuilderExtensions
{
    internal static void WriteHeader(this CSharpFormatter cs)
    {
        cs.AppendLine("// -----------------------------------------------------");
        cs.AppendLine("// Copyright (C) 2023 Vertical Software");
        cs.AppendLine("// Use of this source code is governed by an MIT-style");
        cs.AppendLine("// license that can be found in the LICENSE file or at");
        cs.AppendLine("// https://opensource.org/licenses/MIT.");
        cs.AppendLine("// <auto-generated/>");
        cs.AppendLine("// -----------------------------------------------------");
    }

    internal static void WriteUsingStatements(this CSharpFormatter cs, params string[] namespaces)
    {
        foreach (var @namespace in namespaces)
        {
            cs.AppendLine($"using {@namespace};");
        }

        cs.AppendLine();
    }

    internal static void WriteNullableEnable(this CSharpFormatter cs)
    {
        cs.AppendLine("#nullable enable");
        cs.AppendLine();
    }
}